apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
  namespace: tasky
rules:
- apiGroups:
  - 'extensions, apps'
  resources:
  - 'deployments'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'